# Generated by Django 4.2 on 2024-09-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Shipping Amount'),
        ),
    ]
