# Generated by Django 4.2 on 2024-09-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
