# Generated by Django 4.2 on 2024-09-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_review_reply_alter_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
