# Generated by Django 4.2 on 2024-09-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='status',
        ),
    ]
